version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - dotnet-install.sh --jsonfile global.json
      - $(aws ecr get-login --no-include-email)
      - pip3 install cfn-lint

  build:
    commands:
      - dotnet publish -c Release

      - ./deploy/create-config-files.sh
      - mv deploy/mutedac.template.yml deploy/mutedac.template.yml.bak
      - |
        aws cloudformation package \
          --template-file deploy/mutedac.template.yml.bak \
          --output-template-file deploy/mutedac.template.yml \
          --s3-bucket $ARTIFACT_STORE \
          --s3-prefix lambdas

      - mv deploy/shared-utilities.template.yml deploy/shared-utilities.template.yml.bak
      - |
        aws cloudformation package \
          --template-file deploy/shared-utilities.template.yml.bak \
          --output-template-file deploy/shared-utilities.template.yml \
          --s3-bucket $ARTIFACT_STORE \
          --s3-prefix lambdas

      - cfn-lint deploy/mutedac.template.yml
      - cfn-lint deploy/shared-utilities.template.yml

artifacts:
  discard-paths: yes
  files:
    - "deploy/mutedac.template.yml"
    - "deploy/shared-utilities.template.yml"
    - "mutedac.*.config.json"
