version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - pip install cfn-lint

  build:
    commands:
      - cfn-lint deploy/mutedac.template.yml

      - IMAGE=$REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker build -t $IMAGE src/ClusterStarter
      - ./deploy/create-config-files.sh $IMAGE

artifacts:
  discard-paths: yes
  files:
    - "deploy/mutedac.template.yml"
    - "mutedac.*.config.json"
