Transform: AWS::Serverless-2016-10-31
Parameters:
  DevClusterName:
    Type: String
    Description: Name of the database cluster in dev

  ProdClusterName:
    Type: String
    Description: Name of the database cluster in prod

  DevStartDatabaseFunctionArn:
    Type: String
    Description: ARN of the start database function in dev

  ProdStartDatabaseFunctionArn:
    Type: String
    Description: ARN of the start database function in prod

Resources:
  DatabaseAvailabilityTopic:
    Type: AWS::SNS::Topic

  DatabaseAvailabilityTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref DatabaseAvailabilityTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: "*"
            Principal:
              AWS:
                - !ImportValue cfn-metadata:DevAccountId
                - !ImportValue cfn-metadata:ProdAccountId

  DatabaseAvailabilityTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref DatabaseAvailabilityTopic
      Protocol: lambda
      Endpoint: !GetAtt StartDatabaseTaskCompleterFunction.Arn

  StartDatabaseTaskCompleterFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - states:SendTaskSuccess
              - states:SendTaskFailure
            Resource: "*"

  StartDatabaseTaskCompleterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Mutedac.StartDatabaseTaskCompleter::Mutedac.StartDatabaseTaskCompleter.StartDatabaseTaskCompleterHandler::Run
      Runtime: dotnetcore3.1
      Timeout: 300
      CodeUri: ../bin/Mutedac.StartDatabaseTaskCompleter/Release/netcoreapp3.1/publish/
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - !Ref StartDatabaseTaskCompleterFunctionPolicy

  StartDatabaseTaskCompleterFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartDatabaseTaskCompleterFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref DatabaseAvailabilityTopic

Outputs:
  DevClusterName:
    Value: !Ref DevClusterName
    Description: Name of the database cluster in dev
    Export:
      Name: !Sub ${AWS::StackName}:DevClusterName

  ProdClusterName:
    Value: !Ref ProdClusterName
    Description: Name of the database cluster in prod
    Export:
      Name: !Sub ${AWS::StackName}:ProdClusterName

  DevStartDatabaseFunctionArn:
    Value: !Ref DevStartDatabaseFunctionArn
    Description: ARN of the start database function in dev
    Export:
      Name: !Sub ${AWS::StackName}:DevStartDatabaseFunctionArn

  ProdStartDatabaseFunctionArn:
    Value: !Ref ProdStartDatabaseFunctionArn
    Description: ARN of the start database function in prod
    Export:
      Name: !Sub ${AWS::StackName}:ProdStartDatabaseFunctionArn

  AvailabilityTopic:
    Value: !Ref DatabaseAvailabilityTopic
    Description: ARN of the database availability topic
    Export:
      Name: !Sub ${AWS::StackName}:AvailabilityTopic
